version: '3'

services:
  object_controller:
    container_name: object_controller
    build:
      context: .
      dockerfile: ./${DOCKERFILE_OC:-DockerfileOCClient}
    ports:
      - "20001:20001/udp"
    volumes:
      - filebeatV:/usr/src/app/log
    stdin_open: true
    tty: true

  sender_rasta:
    build:
      context: .
      dockerfile: ./${DOCKERFILE_RASTA:-DockerfileRastaClient}
    container_name: sender_rasta
    volumes:
      - filebeatV:/usr/src/app/CRasta/logs
    ports:
      - "8888:8888/udp"
      - "8889:8889/udp"

volumes:
  filebeatV: